name: pull
on:
  repository_dispatch:
  workflow_dispatch:
env:
  UBUNTU_ENV: dev-env-ubuntu
  CENTOS_ENV: dev-env-centos7
  IMG_NAME: starrocks
  ALIYUN_REGISTRY_URL: registry.cn-guangzhou.aliyuncs.com
  MY_NAMCESPACE: mydocker_imgs
  MY_ALIYUN_REGISTRY: docker-imgs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line scripts
        run: |
          docker rmi $(docker images -q)
          docker images
          #docker pull $IMG_NAME/$CENTOS_ENV:2.5-latest
          docker login --username=${{ secrets.USER_NAME }} --password=${{ secrets.PASSWD }} $ALIYUN_REGISTRY_URL
          #docker tag $IMG_NAME/$CENTOS_ENV:2.5-latest $ALIYUN_REGISTRY_URL/$MY_NAMCESPACE/$MY_ALIYUN_REGISTRY:$CENTOS_ENV-2.5-latest
          #docker push $ALIYUN_REGISTRY_URL/$MY_NAMCESPACE/$MY_ALIYUN_REGISTRY:$CENTOS_ENV-2.5-latest
          echo -e "2.5-latest\n3.0-latest\n3.1-latest" >img_version.txt
          for i in `cat img_version.txt`;do docker pull $IMG_NAME/$CENTOS_ENV:${i} && docker pull $IMG_NAME/$UBUNTU_ENV:${i} ;done
          docker images
          # tag
          for i in `cat img_version.txt`;do docker tag $IMG_NAME/$CENTOS_ENV:${i} $ALIYUN_REGISTRY_URL/$MY_NAMCESPACE/$MY_ALIYUN_REGISTRY:$IMG_NAME-$CENTOS_ENV-${i};done
          for i in `cat img_version.txt`;do docker tag $IMG_NAME/$UBUNTU_ENV:${i} $ALIYUN_REGISTRY_URL/$MY_NAMCESPACE/$MY_ALIYUN_REGISTRY:$IMG_NAME-$UBUNTU_ENV-${i};done
          # push
          for i in `cat img_version.txt`;do docker push $ALIYUN_REGISTRY_URL/$MY_NAMCESPACE/$MY_ALIYUN_REGISTRY:$IMG_NAME-$CENTOS_ENV-${i};done
          for i in `cat img_version.txt`;do docker push $ALIYUN_REGISTRY_URL/$MY_NAMCESPACE/$MY_ALIYUN_REGISTRY:$IMG_NAME-$UBUNTU_ENV-${i};done
