name: pull
on:
  repository_dispatch:
  workflow_dispatch:
env:
  UBUNTU_ENV: dev-env-ubuntu
  CENTOS_ENV: dev-env-centos7
  IMG_NAME: starrocks
  ALIYUN_REGISTRY_URL: registry.cn-guangzhou.aliyuncs.com
  MY_NAMCESPACE: mydocker_imgs
  MY_ALIYUN_REGISTRY: docker-imgs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line scripts
        run: |
          docker pull $IMG_NAME/$CENTOS_ENV:2.5-latest
          docker login --username=${{ secrets.USER_NAME }} --password=${{ secrets.PASSWD }} $ALIYUN_REGISTRY_URL
          docker tag $IMG_NAME/$CENTOS_ENV:2.5-latest $ALIYUN_REGISTRY_URL/$MY_NAMCESPACE/$IMG_NAME/$MY_ALIYUN_REGISTRY:2.5-latest
          docker push $ALIYUN_REGISTRY_URL/$MY_NAMCESPACE/$MY_ALIYUN_REGISTRY:2.5-latest
